### ISSUE TITLE
ssh Permission denied (publickey).

### ISSUE THREAD

**Issue by SX-GitHub** [f0cal/google-coral#11]
* Doc you were trying to follow: https://coral.withgoogle.com/docs/dev-board/reflash/
* Your host OS: Debian ARM64 stretch
* Your Python3 version: N/A

# ssh mendel@192.168.100.2

# should show password:

# I got error "ssh Permission denied (publickey)."
-- I was able to ssh to 2.0 Beaker minutes ago before flash and reboot!

[coral_board_ssh_log.txt](https://github.com/f0cal/google-coral/files/3101589/coral_board_ssh_log.txt)

**Comment by SX-GitHub** [comment]
OK the answer is in the bottom part of the page https://coral.withgoogle.com/docs/dev-board/mdt/#connect-to-a-boards-shell

**Comment by prasad456** [comment]
> OK the answer is in the bottom part of the page https://coral.withgoogle.com/docs/dev-board/mdt/#connect-to-a-boards-shell

apt-get not working for mac os?
