### ISSUE TITLE
kernel source code for the Coral kit

### ISSUE THREAD

**Issue by dilipkumar25** [f0cal/google-coral#28]
Does anyone have the kernel source code for the Coral Dev kit? If available, the source code to the entire BSP (rootfs, libaries etc.) would be helpful too...

**Comment by larrylart** [comment]
https://coral.googlesource.com/
However, I don't think they've made the source code for libraries available, at least not yet.

**Comment by Namburger** [comment]
You can download it here: https://coral.googlesource.com/docs/+/refs/heads/master/GettingStarted.md
