### ISSUE TITLE
Image Regression with EdgeTPU

### ISSUE THREAD

**Issue by TannerGilbert** [f0cal/google-coral#34]
How can I perform Image Regression on the USB Accelerator with the Python API.

### What I tried
I tried using the ClassificationEngine without label but it didn't seem to work.

Any tip would be greatly appreciated.

**Comment by YaroslavSchubert** [comment]
You should be able to run regression network using BasicEngine. ClassificationEngine and  DetectionEngine are just a wrapper around BasicEngine.

**Comment by TannerGilbert** [comment]
Fixed with the BasicEngine or using the tflite runtime
