### ISSUE TITLE
Trial Coral USB accelerator example crashed

### ISSUE THREAD

**Issue by AlexTraan** [f0cal/google-coral#36]
* Doc you were trying to follow: https://coral.googlesource.com/edgetpu-native/+/refs/heads/release-chef/edgetpu/cpp/examples
* Your host OS: ubuntu 18.04 LTS and Coral USB Accelerator
* Your Python3 version: 

# What I ran
i run two_models_one_tpu.cc file

# What actually happened
I get the source code from (https://coral.googlesource.com/edgetpu-native/+/refs/heads/release-chef/edgetpu/cpp/examples), however the executable program met segmentation fault at this code block: "auto input = interpreter->typed_tensor<float>(0);" in ResizeImage function, after traceback:
////////////////////////
TfLiteTensor* tensor(int tensor_index) {
    if (tensor_index < 0 ||
        static_cast<size_t>(tensor_index) >= context_.tensors_size) { // <-- segmentation in here
        return nullptr;
    }
////////////////////////    
although interpreter->AllocateTensors() return OK

Can you help?

**Comment by Namburger** [comment]
@AlexTraan 
How did you compile it?
