### ISSUE TITLE
no output when running fastboot devices command

### ISSUE THREAD

**Issue by rahul4tripathi2** [f0cal/google-coral#41]
* Doc you were trying to follow: <https://coral.withgoogle.com/docs/dev-board/get-started/>
* Your host OS: <LINUX 18.04>
* Your Python3 version: <Python 3.6.8>

# What I ran
fastboot devices

# What the docs said should happen
1b0741d6f0609912        fastboot

# What actually happened
No output

**Comment by brian-yu** [comment]
Also running into this problem on MacOS 10.14.6, Python 3.6.7, and fastboot version 29.0.2-5738569.

**Comment by rahul4tripathi2** [comment]
Hi I've solved this problem
Solution -  please try with multiple type C cables until fastboot devices show your devices for me 3rd time changing type C worked!!!.
