### ISSUE TITLE
Issues while Flashing the Board

### ISSUE THREAD

**Issue by Sureshee** [f0cal/google-coral#44]
Hi,
Doc you were trying to follow:
I tried following the procedure given in the coral webpage. 
https://coral.withgoogle.com/docs/dev-board/get-started/#requirements

Your host OS:
macOS Mojave 10.14.6

Your Python3 version:
Python 3.6.1

What I ran
It went through step 6 until "Download and flash the system image". When i execute  bash flash.sh, it always never exits out of this step. I don't get a prompt to see the username and password.

What the docs said should happen
It said that the Flashing process will print several output.
 It takes about 5 minutes to complete. When it's done, the system reboots and the console prompts you to login. (The login prompt might be obscured by some logs, so press Enter when you notice the logging has stopped.)

What actually happened
When bash flash.sh gets executed, It reports Writing "bootloader 0" DONE!
But request 000000007bf2ec40 was not queued to ep1in-bulk
It never reaches Step7.

<img width="1143" alt="Screenshot 2019-08-25 at 22 40 39" src="https://user-images.githubusercontent.com/16618701/63655551-77734200-c789-11e9-8e63-62053ae86338.png">

**Comment by victor045** [comment]
Had the same problem, I just changed the power adapter to a bigger one with more amperes.

![WhatsApp Image 2019-09-06 at 11 12 51 PM](https://user-images.githubusercontent.com/43472498/64469703-54874d00-d0fc-11e9-94b2-dcea68635575.jpeg)
.
