### ISSUE TITLE
Can't get my own videos working with edgetpu_demo

### ISSUE THREAD

**Issue by lunzueta** [f0cal/google-coral#47]
* Doc you were trying to follow: https://coral.withgoogle.com/docs/dev-board/get-started/#run-a-model-on-the-edge-tpu
* Your host OS: Ubuntu 16.04.6 LTS (host PC) and Mendel 3 (Google Coral Board)
* Your Python3 version: 3.5.3 (Google Coral Board)

# What I ran
I just wanted to execute the edgetpu_demo bash script in the Google Coral Board, but replacing the videos that it brings by default (video_device.mp4 and video_stream.mp4) by others of my interest. I get a segmentation fault error that I don't get with the default videos. I used ffmpeg to convert my videos to the .mp4 format (following [this](https://superuser.com/questions/438390/creating-mp4-videos-ready-for-http-streaming)). I'm not a ffmpeg expert. Debugging the code, the problem appears in the function `info = gstreamer.get_video_info(filename)`, located at `/usr/lib/python3/dist-packages/edgetpuvision/camera.py(67)__init__()`. I suspect that I didn't generate the .mp4 file in the way that Coral needs, but I can see the video normally. My video is 640x480 and I just used the streaming demo. I also tried with other resolutions without luck.

# What the docs said should happen
This isn't documented, but I think that it should run in the same way as with the default videos.

# What actually happened
The program raises a "Segmentation fault".

**Comment by Namburger** [comment]
@lunzueta try this:
```
ffmpeg -i test.mp4 -an -vf "scale=960:540,format=yuv420p" -colorspace bt470bg -color_range tv -color_primaries smpte170m -color_trc bt709 -vcodec libx264 -brand mp42 -c:v libx264 -profile:v baseline video_stream.mp4
```
