### ISSUE TITLE
Coral get's hot and doesn't activate the FAN causes: mmcblk0: error -84 transferring data

### ISSUE THREAD

**Issue by mcanerim** [f0cal/google-coral#49]
I'm simply running a pip3 install face_recognition and after everything is downloaded successfully I'm getting the following error while the Coral Board tries to run the setup.py for the package.

The error is as following,

[ 4654.563095] mmcblk0: retrying using single block read
[ 4664.981981] mmcblk0: error -84 transferring data, sector 9880576, nr 256, cmd response 0x900, card status 0xb00
[ 4671.892082] mmcblk0: error -84 transferring data, sector 9886160, nr 256, cmd response 0x900, card status 0xb00
[ 4675.414611] mmcblk0: error -84 transferring data, sector 2148752, nr 256, cmd response 0x900, card status 0xb00
[ 4693.436395] mmcblk0: error -84 transferring data, sector 2148728, nr 256, cmd response 0x900, card status 0xb00
[ 5098.073260] mmcblk0: error -84 transferring data, sector 2148728, nr 256, cmd response 0x900, card status 0xb00
[ 5151.520954] mmcblk0: error -84 transferring data, sector 2148728, nr 200, cmd response 0x900, card status 0xb00
[ 5168.964275] mmcblk0: error -84 transferring data, sector 9886168, nr 256, cmd response 0x900, card status 0xb00
[ 5187.535621] mmcblk0: error -84 transferring data, sector 2148728, nr 184, cmd response 0x900, card status 0xb00
[ 5188.123174] mmcblk0: error -84 transferring data, sector 9886168, nr 256, cmd response 0x900, card status 0xb00
[ 5203.396207] mmcblk0: error -84 transferring data, sector 9886168, nr 256, cmd response 0x900, card status 0xb00
[ 5223.443948] mmcblk0: error -84 transferring data, sector 2148768, nr 256, cmd response 0x900, card status 0xb00
[ 5229.895087] mmcblk0: error -84 transferring data, sector 9675032, nr 256, cmd response 0x900, card status 0xb00
[ 5239.354025] mmcblk0: error -84 transferring data, sector 2148776, nr 208, cmd response 0x900, card status 0xb00
[ 5603.233123] mmcblk0: error -84 transferring data, sector 2036832, nr 256, cmd response 0x900, card status 0xb00
[ 5694.772034] mmcblk0: error -84 transferring data, sector 2148728, nr 256, cmd response 0x900, card status 0xb00
[ 5706.741601] mmcblk0: error -84 transferring data, sector 9886168, nr 256, cmd response 0x900, card status 0xb00
[ 5715.635896] mmcblk0: error -84 transferring data, sector 2036848, nr 256, cmd response 0x900, card status 0xb00
[ 5719.206999] mmcblk0: error -84 transferring data, sector 2148728, nr 256, cmd response 0x900, card status 0xb00
[ 5735.527722] mmcblk0: error -84 transferring data, sector 2148728, nr 240, cmd response 0x900, card status 0xb00
[ 5740.046372] mmcblk0: error -84 transferring data, sector 2148728, nr 256, cmd response 0x900, card status 0xb00
[ 5742.686479] mmcblk0: error -84 transferring data, sector 9670992, nr 136, cmd response 0x900, card status 0xb00

This continues for hours even days if I don't stop the execution.

I have tried to restart the board it doesn't work.

mmcblk0 is the internal storage of the device.

**Comment by mcanerim** [comment]
The current thing is that I have discovered that when properly cooled the problem does not occur. I have connected the FAN of the coral board into an external power source to keep it running all the time, but this is no solution to hold on for me.

**Comment by zorrobyte** [comment]
Same here, crashes every time I try to compile something in C. I even tried setting the fan to 100%
libtool: compile:  g++ -DHAVE_CONFIG_H -I. -I./src -I./src -DKJ_HEADER_WARNINGS -DCAPNP_HEADER_WARNINGS -DCAPNP_INCLUDE_DIR=\"/usr/local/include\" -pthread -fPIC -pthread -MT src/capnp/compiler/lexer.lo -MD -MP -MF src/capnp/compiler/.deps/lexer.Tpo -c src/capnp/compiler/lexer.c++ -o src/capnp/compiler/lexer.o >/dev/null 2>&1
[  726.210412] mmcblk0: error -84 transferring data, sector 2036928, nr 256, cmd response 0x900, card status 0xb00

**Comment by zorrobyte** [comment]
@mcanerim this is due to running out of RAM. Allocate a swapfile

**Comment by lleonid** [comment]
Upcoming mendel release should address original problem.

**Comment by Namburger** [comment]
This is fixed

**Comment by derekm** [comment]
I have this issue on 5.2 Eagle.

Had to follow instructions here to turn fan on continuously: https://stackoverflow.com/a/58385364

**Comment by derekm** [comment]
Fix is:
```sh
sudo -i
apt install sysfsutils
echo "class/thermal/thermal_zone0/trip_point_4_temp = 50000" >> /etc/sysfs.conf
reboot
```
