### ISSUE TITLE
EdgeTPU library is not updating for dev board

### ISSUE THREAD

**Issue by sanchitjain04** [f0cal/google-coral#51]
* Doc you were trying to follow: https://coral.withgoogle.com/news/updates-07-2019/
* Your host OS: Ubuntu 16.04
Python3 version: 3.5.3

I executed the commands as mentioned in the post as mentioned above :

sudo apt-get update

sudo apt-get dist-upgrade

this automatically updates the edgetpu library along with other Mendel system software.

As per the post it should have updated the library but after updates were done the edgetpu library version is still been shown as 1.2.0

But our expectations were to be updated to newest 2.11.1 version

Kindly help in resolving the issue.

**Comment by Namburger** [comment]
Ahh if you have mendel 2.0, dist-upgrade won't do it. Unfortunately for now, you'll need to reflash the board with the newest image.
