### ISSUE TITLE
Mendel Linux Release 3.0 Chef (Apr 2019) Source Code Location/Tag

### ISSUE THREAD

**Issue by dbaba** [f0cal/google-coral#52]
I'm looking for [Mendel Linux Release 3.0 Chef (Apr 2019)](https://coral.withgoogle.com/resources/#mendel-linux-os) Source Code in order to build some missing kernel modules on the prebuilt image but I couldn't identify the location and the actual tag/branch.

There are a lot of [repos at googlesource.com](https://coral.googlesource.com/?format=HTML) and I found these candidate repos in the page.

- [linux-imx](https://coral.googlesource.com/linux-imx/)
- [linux-imx-debian](https://coral.googlesource.com/linux-imx-debian/)

However, the former seems to be old and the latter doesn't seem to have 4.9.51-imx kernel branch.
Does anyone have any idea of the repo project location and the tag for the release?

**Comment by lleonid** [comment]
https://coral.googlesource.com/docs/+/refs/heads/release-chef/GettingStarted.md explicitly tells how to build Chef version.
