### ISSUE TITLE
kernel feature "cgroups freezer" missing

### ISSUE THREAD

**Issue by hacker-h** [f0cal/google-coral#55]
Mendel GNU/Linux 3 (Chef) lacks of the cgroups freezer kernel feature, which is mandatory for e.g. kubernetes. Can it be patched?

**Comment by Namburger** [comment]
Based on [this](https://cateee.net/lkddb/web-lkddb/CGROUP_FREEZER.html), I believe you can turn it on the same way as this issue: https://github.com/f0cal/google-coral/issues/56 :)
With this turn on:
```
CONFIG_CGROUP_FREEZER=y
```
Although I'd first try installing Mendel Day (4.0). It has a newer kernel and more new features
