### ISSUE TITLE
CONFIG_NETFILTER_XT_MATCH_COMMENT not set

### ISSUE THREAD

**Issue by hacker-h** [f0cal/google-coral#56]
`CONFIG_NETFILTER_XT_MATCH_COMMENT` is not set which will cause trouble when loading iptables rulesets with comments.

**Comment by Namburger** [comment]
@hacker-h is that a kernel config (sorry, not an expert on k3)?
any how, if it is a kernel config, you can recompile the kernel with it turned on.
1) Get the source code from [here](https://coral.googlesource.com/docs/+/refs/heads/master/GettingStarted.md)
2) Open [packages/linux-imx/debian/defconfig]() and add 
```
CONFIG_NETFILTER_XT_MATCH_COMMENT=y
```
3) compile with `m docker-linux-imx`
4) The kernel will be packaged as a debian package in `out/target/product/imx8m_phanbell/packages/bsp/linux-image-4.14.98-imx_11–4_arm64.deb`
You can scp that to the dev board and install using `dpkg`

Cheers!
