### ISSUE TITLE
Parse error in /etc/sudoers near line 28 when doing `sudo apt-get update`

### ISSUE THREAD

**Issue by pliablepixels** [f0cal/google-coral#60]
* Doc you were trying to follow: https://coral.ai/docs/dev-board/get-started/
* Your host OS:  OSX Mojave 10.14.6
* Your Python3 version: 3.6.8 (host)

# What I ran
```
sudo apt-get update
```

# What the docs said should happen
Should initiate packages updates (step 1 of 2)

# What actually happened
```
mendel@coy-jet:~$ sudo apt-get update
>>> /etc/sudoers: syntax error near line 28 <<<
sudo: parse error in /etc/sudoers near line 28
sudo: no valid sudoers sources found, quitting
sudo: unable to initialize policy plugin
```

**More info:**
Production  date of Coral 9327A
I don't see any information on how to get root access, so I can fix things or view the sudoers file.
mendel package downloaded and installed: https://dl.google.com/coral/mendel/enterprise/mendel-enterprise-day-13.zip

**Comment by pliablepixels** [comment]
closing - reflashing again worked

**Comment by gte620v** [comment]
How did you do the reflashing?  re-entering the bootloader seems to require sudo: https://coral.googlesource.com/mdt/+/refs/heads/master/mdt/shell.py#123

I have the same issue as well as another possibly related issue that is keeping me from being able to ssh to my coral board.  So I only have serial `mendel` user access to the board and I am unsure how to proceed.

**Comment by gte620v** [comment]
Nevermind.  I see you can get back into `fastboot 0` mode by connected to serial before you add USB-C power from the board.  From there, I can enter u-boot and get run `fastboot 0`.
