### ISSUE TITLE
how to set auto-start a application？I can not find rc.local in /etc .

### ISSUE THREAD

**Issue by dinghuawen** [f0cal/google-coral#64]
how to set auto-start a application？I can not find rc.local in /etc

**Comment by aaroninaustin** [comment]
So you'll want to use `systemd` - I hadn't done it in a while myself and followed this guide:

https://www.digitalocean.com/community/tutorials/how-to-use-systemctl-to-manage-systemd-services-and-units

My only tips to add would be that actually create the services file you'll edit a new one and get a blank file to drop the service config in...

`sudo systemctl edit yourapp.service`

From that point you can start with something like this to get a service initialized. After which you'll
enable it for startup `sudo systemctl enable yourapp.service`

```
[Unit]
Description=Your App
After=network.target
StartLimitIntervalSec=0

[Service]
Type=simple
Restart=always
RestartSec=1
User=mendel
ExecStart=/usr/bin/bash /home/mendel/script.sh

[Install]
WantedBy=multi-user.target
```

**Comment by Namburger** [comment]
Honorable mention: https://github.com/google-coral/edgetpu/issues/120#issuecomment-630814040
