### ISSUE TITLE
Gibberish words seen after running screen 

### ISSUE THREAD

**Issue by Prem95** [f0cal/google-coral#71]
* Doc you were trying to follow: https://coral.withgoogle.com/docs/dev-board/get-started/
* Your host OS: Ubuntu 18.04 LTS on Mac OS Catalina (Virtual Box)
* Your Python3 version: Python 3.7

# What I ran

`screen /dev/ttyUSB0`

# What the docs said should happen

The Coral will be booted until a login with random hostname appears. 

# What actually happened

Gibberish words on the screen indicating the comms are not working as intended. But still able to login later on.

<img width="748" alt="Screenshot 2020-02-12 at 10 35 33 PM" src="https://user-images.githubusercontent.com/13019570/74345051-6d510880-4de8-11ea-8698-dd388479e713.png">

**Comment by Namburger** [comment]
@Prem95 Ensure to include the baud rate, without setting the correct baud rate, screen will misinterpret the serial data:
```
screen /dev/ttyUSB0 115200
```
