### ISSUE TITLE
Couldn't establish a cellular connection with a USB modem

### ISSUE THREAD

**Issue by sagilar** [f0cal/google-coral#76]
I've been working with the coral edge tpu for more than a year; even I updated the OS version to mendel 4. Everything was right working with the new OpenCV support and those things, but now I need to establish a connection to access Internet using a cellular modem (module U-Blox SARA R410M) and it hasn't been possible with the mendel OS. I've tried with Windows (10) and Ubuntu with the same modem and the connection work in both OSs, this means that the module works for that.
So, I tried to replicate the same of the Ubuntu case on the Coral board, using `wvdial` and `nmcli` but noone seems to work. The wvdial, which uses PPP, can access the module via AT commands and initializes the communication well, but when trying to establish the ppp internet interface it returns `the PPP daemon has died. (exit code = 4)` which means `no PPP kernel support`. When using the NetworkManager cli (nmcli), which bases on the ModemManager to set up the modem correctly, can't even find the modems attached to the USB port.
So, using a coral devboard, an item which is supposed to be employed in Internet of Things applications, but without support for cellular connectivity doesn't make sense at all.
Is there any way to solve this and achieve a cellular connection with USB modems? I appreciate your help and guidance. Thank you in advance.

**Comment by Namburger** [comment]
Duplicate, let's keep communication here: https://github.com/google-coral/edgetpu/issues/128
