### ISSUE TITLE
ModuleNotFoundError: No module named 'edgetpu'

### ISSUE THREAD

**Issue by alitillawi** [f0cal/google-coral#77]
* Doc trying to follow: https://coral.ai/docs/accelerator/get-started/#1c-on-windows
* Host OS: Windows 10
* Python3 version: 3.6.5

# What I ran:
-Pre-configuration and runtime for the edge TPU on windows were made
-Code for facial recognition via a TFlite trained model.

# What happened
    from edgetpu.classification.engine import ClassificationEngine
ModuleNotFoundError: No module named 'edgetpu'

**Comment by Namburger** [comment]
Hey, since you've started the issue [here](https://github.com/google-coral/edgetpu/issues/158) also, lets keep communication there.
FYI, that is a standard python error for the package not being installed.
