### ISSUE TITLE
Help mapping a NAS drive

### ISSUE THREAD

**Issue by mikelittlerock** [f0cal/google-coral#79]
tried syntax i have used on other unix sytems but not able to map a drive to my NAS yet.. any tips welcomed.

**Comment by brianthelion** [comment]
@mikelittlerock Please post detailed logs of your attempts. Thanks.

**Comment by Namburger** [comment]
@mikelittlerock 
DevBoard comes with MendelOS, the current released version is a fork of debian buster so I doubt that it would be different than other linux system. What's the issue and what have you tried?

**Comment by mikelittlerock** [comment]
got it working last night
the nas (qnap) supports NFS so just tried "sudo mount -t nfs 192.168.128.181:/surveillance /home/surveillance "
and that worked fine. 
Thanks!
