### ISSUE TITLE
Play wav sound 

### ISSUE THREAD

**Issue by laurentdebricon** [f0cal/google-coral#82]
How to play a wav file through the 3.5mm audio jack

it looks simple but i am failing hard :(

**Comment by laurentdebricon** [comment]
```
#!/usr/bin/env python3

from playsound import playsound

def playy():
    playsound('xylofon.wav')
    
from threading import Thread
T = Thread(target=playy) # create thread
T.start() # Launch created thread    

while True:
    print('cool')
```

**Comment by laurentdebricon** [comment]
I checked first that everything was ok with this simple command :
`speaker-test -c 2 -t wav`

**Comment by dinghuawen** [comment]
@laurentdebricon ，
Have you solved this problem ？ how can I play a audio sample? I followed your steps, but I didn't succeed. Thanks！
