### ISSUE TITLE
README.md is misleading

### ISSUE THREAD

**Issue by jtgans** [f0cal/google-coral#9]
Under OS Notes is the following:

> Given the observations below (primarily the libc version) the OS appears to be an upgraded-to-testing version of Debian 9.0 (Stretch). This knowledge allows us to access Debian sources without much concern.

This is actually incorrect. Debian is based upon stock Debian Stretch -- not testing. Source: I'm the techlead on Mendel. :smile:

**Comment by brianthelion** [comment]
@jtgans Very nice to have you checking in with us! I will update the notes.
