### ISSUE TITLE
Can't pip install certain python3 modules

### ISSUE THREAD

**Issue by murreletinnovation** [f0cal/google-coral#93]
I'm working on a Dev Board running Mendel GNU/Linux 5 (Eagle) Release 10.0
GCC: 8.3.0
Python3 version: 3.7.3

What I ran:
sudo pip3 install pandas (or scipy and a few other examples)

I've attached the output of trying to pip install pandas.
[output.txt](https://github.com/f0cal/google-coral/files/5823439/output.txt)

**Comment by Namburger** [comment]
You can install using sudo:
```
mendel@green-valet:~$ sudo apt install python3-pandas
```
If a pip library doesn't have a pip package specifically for a certain platform, it usually requires building it, which will fails if your system doesn't have a certain dependencies

**Comment by murreletinnovation** [comment]
Thanks @Namburger, was confused as to why the python wheels were failing. Closing this issue
